language: python
python:
  - 3.7
  - 3.8
  - 3.9
cache: pip
jobs:
  fast_finish: true
  allow_failures:
    - python: 3.8
    - python: 3.9
install:
  - pip install -U setuptools
  - pip install -U pip
  - pip install .
  - pip install -U .[test]
script:
  - python setup.py test
deploy:
  provider: pypi
  username: "__token__"
  password: $PYPI_TOKEN
  skip_existing: true
  on:
    tags: true
